### ISSUE TITLE
SyntaxError: Unexpected token u

### ISSUE THREAD

**Issue by RobinDaugherty** [jamieforrest/github-asana#15]
Both locally and on heroku, I'm getting the following fatal error:

```
undefined:1
undefined
^
SyntaxError: Unexpected token u
    at Object.parse (native)
    at Object.<anonymous> (./github-asana/lib/github-asana.js:5:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/robind/Dropbox/mlw2/github-asana/app.js:6:20)
    at Module._compile (module.js:456:26)
```

Here are the node modules in use:

```
zlib@1.0.5 node_modules/zlib

express@2.5.8 node_modules/express
├── qs@0.4.2
├── mime@1.2.4
├── mkdirp@0.3.0
└── connect@1.9.2 (formidable@1.0.14)

request@2.34.0 node_modules/request
├── json-stringify-safe@5.0.0
├── forever-agent@0.5.2
├── aws-sign2@0.5.0
├── qs@0.6.6
├── tunnel-agent@0.3.0
├── oauth-sign@0.3.0
├── mime@1.2.11
├── node-uuid@1.4.1
├── hawk@1.0.0 (cryptiles@0.2.2, sntp@0.2.4, boom@0.4.2, hoek@0.9.1)
├── form-data@0.1.2 (async@0.2.10, combined-stream@0.0.4)
├── tough-cookie@0.12.1 (punycode@1.2.4)
└── http-signature@0.10.0 (assert-plus@0.1.2, asn1@0.1.11, ctype@0.5.2)
```

**Comment by RobinDaugherty** [comment]
It looks like the ASANA_USERS environment variable is required. Documentation doesn't reflect this.
